spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: vim_dba
    password: admin
    url: jdbc:postgresql://localhost:7432/vim_db
logging:
  level:
    be.mathiasbosman.vim: trace
server:
  port: 8081

keycloak:
  realm: vim
  auth-server-url: http://localhost:8180/auth
  ssl-required: external
  resource: vim-api
  credentials:
    secret: 070a8271-1bc7-4a52-807b-bde29fc41d24
  use-resource-role-mappings: true
  autodetect-bearer-only: true