spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: vim_dba
    password: admin
    url: jdbc:postgresql://localhost:7432/vim_db
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org.hibernate.type.descriptor.sql: trace
    be.mathiasbosman.vim: trace
server:
  port: 8081