name: Publish
on:
  release:
    types: [ published ]

env:
  ACTION_ACTOR_EMAIL: ${{ secrets.ACTION_ACTOR_EMAIL }}

jobs:
  test:
    name: Test run 🧪
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt
      - name: Maven verify
        run: mvn -B verify

  prepare-deploy:
    name: Update version 🌿
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACTION_PAT }}
      - name: Remove snapshot
        run: |
          mvn versions:set -DremoveSnapshot versions:commit
      - name: Commit version
        run: |
          git config user.name "githubaction[bot]"
          git config user.email "$ACTION_ACTOR_EMAIL"
          git commit -am "[GitHub action] prepare for release"
          git push origin HEAD:master

  deploy:
    name: Deploy 🚀
    needs: prepare-deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACTION_PAT }}
      - name: Pull new version
        run: |
          git config user.name "githubaction[bot]"
          git config user.email "$ACTION_ACTOR_EMAIL"
          git pull origin master --no-rebase
      - name: Publish package
        run: mvn -B deploy -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  post-deploy:
    name: Prepare snapshot 🌱
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACTION_PAT }}
      - name: Pull new version
        run: |
          git config user.name "githubaction[bot]"
          git config user.email "$ACTION_ACTOR_EMAIL"
          git pull origin master --no-rebase
      - name: Set snapshot version
        run: |
          mvn build-helper:parse-version versions:set -DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.\${parsedVersion.nextIncrementalVersion}-SNAPSHOT versions:commit
      - name: Commit snapshot version
        run: |
          git commit -am "[GitHub action] prepare for next development iteration"
          git push origin HEAD:master