version: '3'
volumes:
  postgres_data:
    driver: local

services:
  vim-local-db:
    image: postgres
    ports:
      - '7432:5432'
    environment:
      - POSTGRES_DB=vim_db
      - POSTGRES_USER=vim_dba
      - POSTGRES_PASSWORD=admin
  vim-keycloak-local-db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
  vim-local-keycloak:
    image: wizzn/keycloak:14
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: vim-keycloak-local-db
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
      KEYCLOAK_LOGLEVEL: DEBUG
      ROOT_LOGLEVEL: DEBUG
    ports:
      - "8180:8080"
      - "8443:8443"
    depends_on:
      - vim-keycloak-local-db